name: Run tests
on: [push]
jobs:
  clojure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@4.0
        with:
          # Install just one or all simultaneously
          cli: 1.10.1.693 # Clojure CLI based on tools.deps
          lein: 2.9.1     # or use 'latest' to always provision latest version of leiningen
          boot: 2.8.3     # or use 'latest' to always provision latest version of boot
          
          # (optional) To avoid rate limit errors please provide github token
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Execute clojure code on Linux and MacOS
        run: clojure -M:test 
        shell: bash
